// <auto-generated />
using System;
using CompraProgramada.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProgramada.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302213117_CreateTableT_PARAMETRO_SISTEMA")]
    partial class CreateTableT_PARAMETRO_SISTEMA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompraProgramada.Domain.Entities.Acao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CODIGO");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME_EMPRESA");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("PRECO");

                    b.HasKey("Id");

                    b.ToTable("T_ACAO", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaAggregate.CestaRecomendacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ATIVA");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime>("DataVigencia")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_VIGENCIA");

                    b.HasKey("Id");

                    b.ToTable("T_CESTA_RECOMENDACAO", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaAggregate.CestaRecomendacaoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcaoId")
                        .HasColumnType("int")
                        .HasColumnName("ACAO_ID");

                    b.Property<int>("CestaRecomendacaoId")
                        .HasColumnType("int")
                        .HasColumnName("CESTA_RECOMENDACAO_ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PERCENTUAL");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("CestaRecomendacaoId");

                    b.ToTable("T_CESTA_RECOMENDACAO_ITEM", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ClienteAggregate.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ADESAO");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_SAIDA");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("ValorAporteMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_APORTE_MENSAL");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("T_CLIENTE", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ClienteAggregate.ContaGrafica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("CLIENTE_ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("T_CONTA_GRAFICA", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ClienteAggregate.CustodiaFilhote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcaoId")
                        .HasColumnType("int")
                        .HasColumnName("ACAO_ID");

                    b.Property<int>("ContaGraficaId")
                        .HasColumnType("int")
                        .HasColumnName("CONTA_GRAFICA_ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<decimal>("PrecoMedio")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("PRECO_MEDIO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("ContaGraficaId", "AcaoId")
                        .IsUnique();

                    b.ToTable("T_CUSTODIA_FILHOTE", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaMasterAggregate.ContaMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("T_CONTA_MASTER", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaMasterAggregate.CustodiaMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcaoId")
                        .HasColumnType("int")
                        .HasColumnName("ACAO_ID");

                    b.Property<int>("ContaMasterId")
                        .HasColumnType("int")
                        .HasColumnName("CONTA_MASTER_ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<decimal>("PrecoMedio")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("PRECO_MEDIO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("ContaMasterId", "AcaoId")
                        .IsUnique();

                    b.ToTable("T_CUSTODIA_MASTER", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompraAggregate.Distribuicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcaoId")
                        .HasColumnType("int")
                        .HasColumnName("ACAO_ID");

                    b.Property<int>("ContaGraficaId")
                        .HasColumnType("int")
                        .HasColumnName("CONTA_GRAFICA_ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_DISTRIBUICAO");

                    b.Property<int>("OrdemCompraId")
                        .HasColumnType("int")
                        .HasColumnName("ORDEM_COMPRA_ID");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("PRECO_UNITARIO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal>("ValorIRDedoDuro")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("VALOR_IR_DEDO_DURO");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("ContaGraficaId");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("T_DISTRIBUICAO", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompraAggregate.OrdemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_EXECUCAO");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.ToTable("T_ORDEM_COMPRA", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompraAggregate.OrdemCompraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcaoId")
                        .HasColumnType("int")
                        .HasColumnName("ACAO_ID");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<int>("OrdemCompraId")
                        .HasColumnType("int")
                        .HasColumnName("ORDEM_COMPRA_ID");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("PRECO_UNITARIO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<int>("TipoMercado")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_MERCADO");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("T_ORDEM_COMPRA_ITEM", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ParametroSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CHAVE");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("T_PARAMETRO_SISTEMA", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaAggregate.CestaRecomendacaoItem", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entities.CestaAggregate.CestaRecomendacao", "CestaRecomendacao")
                        .WithMany("Itens")
                        .HasForeignKey("CestaRecomendacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("CestaRecomendacao");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ClienteAggregate.ContaGrafica", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.ClienteAggregate.Cliente", "Cliente")
                        .WithOne("ContaGrafica")
                        .HasForeignKey("CompraProgramada.Domain.Entities.ClienteAggregate.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ClienteAggregate.CustodiaFilhote", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entities.ClienteAggregate.ContaGrafica", "ContaGrafica")
                        .WithMany("Custodias")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaMasterAggregate.CustodiaMaster", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entities.ContaMasterAggregate.ContaMaster", "ContaMaster")
                        .WithMany("Custodias")
                        .HasForeignKey("ContaMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("ContaMaster");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompraAggregate.Distribuicao", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entities.ClienteAggregate.ContaGrafica", "ContaGrafica")
                        .WithMany()
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entities.OrdemCompraAggregate.OrdemCompra", "OrdemCompra")
                        .WithMany()
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("ContaGrafica");

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompraAggregate.OrdemCompraItem", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entities.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entities.OrdemCompraAggregate.OrdemCompra", "OrdemCompra")
                        .WithMany("Itens")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.CestaAggregate.CestaRecomendacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ClienteAggregate.Cliente", b =>
                {
                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ClienteAggregate.ContaGrafica", b =>
                {
                    b.Navigation("Custodias");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.ContaMasterAggregate.ContaMaster", b =>
                {
                    b.Navigation("Custodias");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entities.OrdemCompraAggregate.OrdemCompra", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
